language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 29abc/multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 29abc/multi-test npm test

after_success:
  - docker build -t 29abc/multi-client ./client
  - docker build -t 29abc/multi-worker ./worker
  - docker build -t 29abc/multi-server ./server
  - docker build -t 29abc/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push 29abc/multi-client
  - docker push 29abc/multi-worker
  - docker push 29abc/multi-server
  - docker push 29abc/multi-nginx 

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-545600923812"
    bucket_path: "multi-docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY_MULTI_DOCKER
    secret_access_key: $AWS_SECRET_KEY_MULTI_DOCKER